package com.example.newsapp.util

import com.example.newsapp.R
import com.example.newsapp.domain.CategoryCardModel
import com.example.newsapp.domain.InterestingCardModel

object Constant {
    val categories = listOf(
        CategoryCardModel(R.string.health),
        CategoryCardModel(R.string.technology),
        CategoryCardModel(R.string.science),
        CategoryCardModel(R.string.culture),
        CategoryCardModel(R.string.art),
    )
    val interestingList = listOf(
        listOf(
            InterestingCardModel(
                R.string.health,
                R.string.interesting_health_title_1,
                R.string.interesting_health_predescription_1,
                R.string.interesting_health_description_1,
                R.drawable.icon_health_interesting_image_1,
                R.drawable.exercising_on_the_beach_royalty_free_image_861966316_1532978122,
            ),
            InterestingCardModel(
                R.string.health,
                R.string.interesting_health_title_2,
                R.string.interesting_health_predescription_2,
                R.string.interesting_health_description_2,
                R.drawable.icon_health_interesting_image_2,
                R.drawable.l_intro_1626268712,
            )
        ),
        listOf(
            InterestingCardModel(
                R.string.technology,
                R.string.interesting_technology_title_1,
                R.string.interesting_technology_predescription_1,
                R.string.interesting_technology_description_1,
                R.drawable.icon_technology_interesting_image,
                R.drawable.icon_full_image_technology_3,
            ),
            InterestingCardModel(
                R.string.technology,
                R.string.interesting_technology_title_2,
                R.string.interesting_technology_predescription_2,
                R.string.interesting_technology_description_2,
                R.drawable.icon_technology_interesting_image_2,
                R.drawable.icon_full_image_technology_4,
            )
        ),
        listOf(
            InterestingCardModel(
                R.string.science,
                R.string.interesting_science_title_1,
                R.string.interesting_science_predescription_1,
                R.string.interesting_science_description_1,
                R.drawable.icon_science_interesting_image,
                R.drawable.icon_full_image_science_3,
            ),
            InterestingCardModel(
                R.string.science,
                R.string.interesting_science_title_2,
                R.string.interesting_science_predescription_2,
                R.string.interesting_science_description_2,
                R.drawable.icon_science_interesting_image_2,
                R.drawable.icon_full_image_science_4,
            )
        ),
        listOf(
            InterestingCardModel(
                R.string.culture,
                R.string.interesting_culture_title_1,
                R.string.interesting_culture_predescription_1,
                R.string.interesting_culture_description_1,
                R.drawable.icon_culture_interesting_image,
                R.drawable.icon_full_image_culture_3,
            ),
            InterestingCardModel(
                R.string.culture,
                R.string.interesting_culture_title_2,
                R.string.interesting_culture_predescription_2,
                R.string.interesting_culture_description_2,
                R.drawable.icon_culture_interesting_image_2,
                R.drawable.icon_full_image_culture_4,
            )
        ),
        listOf(
            InterestingCardModel(
                R.string.art,
                R.string.interesting_art_title_1,
                R.string.interesting_art_predescription_1,
                R.string.interesting_art_description_1,
                R.drawable.icon_art_interesting_image,
                R.drawable.icon_full_image_art_3,
            ),
            InterestingCardModel(
                R.string.art,
                R.string.interesting_art_title_2,
                R.string.interesting_art_predescription_2,
                R.string.interesting_art_description_2,
                R.drawable.icon_art_interesting_image_2,
                R.drawable.icon_full_image_art_4,
            )
        ),
    )
    val trendingList = listOf(
        listOf(
            InterestingCardModel(
                R.string.health,
                R.string.trending_health_title_1,
                R.string.trending_health_predescription_1,
                R.string.trending_health_description_1,
                R.drawable.icon_health_trending_image_1,
                R.drawable.food_restriction_header,
            ),
            InterestingCardModel(
                R.string.health,
                R.string.trending_health_title_2,
                R.string.trending_health_predescription_2,
                R.string.trending_health_description_2,
                R.drawable.icon_health_trending_image_2,
                R.drawable.main_plank_2,
            )
        ),
        listOf(
            InterestingCardModel(
                R.string.technology,
                R.string.trending_technology_title_1,
                R.string.trending_technology_predescription_1,
                R.string.trending_technology_description_1,
                R.drawable.icon_technology_trending_image,
                R.drawable.icon_full_image_technology,
            ),
            InterestingCardModel(
                R.string.technology,
                R.string.trending_technology_title_2,
                R.string.trending_technology_predescription_2,
                R.string.trending_technology_description_2,
                R.drawable.icon_technology_trending_image_2,
                R.drawable.icon_full_image_technology_2,
            )
        ),
        listOf(
            InterestingCardModel(
                R.string.science,
                R.string.trending_science_title_1,
                R.string.trending_science_predescription_1,
                R.string.trending_science_description_1,
                R.drawable.icon_science_trending_image,
                R.drawable.icon_full_image_science,
            ),
            InterestingCardModel(
                R.string.science,
                R.string.trending_science_title_2,
                R.string.trending_science_predescription_2,
                R.string.trending_science_description_2,
                R.drawable.icon_science_trending_image_2,
                R.drawable.icon_full_image_science_2,
            )
        ),
        listOf(
            InterestingCardModel(
                R.string.culture,
                R.string.trending_culture_title_1,
                R.string.trending_culture_predescription_1,
                R.string.trending_culture_description_1,
                R.drawable.icon_culture_trending_image,
                R.drawable.icon_full_image_culture,
            ),
            InterestingCardModel(
                R.string.culture,
                R.string.trending_culture_title_2,
                R.string.trending_culture_predescription_2,
                R.string.trending_culture_description_2,
                R.drawable.icon_culture_trending_image_2,
                R.drawable.icon_full_image_culture_2,
            )
        ),
        listOf(
            InterestingCardModel(
                R.string.art,
                R.string.trending_art_title_1,
                R.string.trending_art_predescription_1,
                R.string.trending_art_description_1,
                R.drawable.icon_art_trending_image,
                R.drawable.icon_full_image_art,
            ),
            InterestingCardModel(
                R.string.art,
                R.string.trending_art_title_2,
                R.string.trending_art_predescription_2,
                R.string.trending_art_description_2,
                R.drawable.icon_art_trending_image_2,
                R.drawable.icon_full_image_art_2,
            )
        ),
    )
}